### ISSUE TITLE
Add website link to main page

### ISSUE THREAD

**Issue by rudeboybert** [weecology/updating-data#8]
Have you considered adding a link to the output website https://www.updatingdata.org/ on the main page of this repo under "About" on the RHS of the page? It would be helpful for those users who don't know the url of the output

**Comment by ethanwhite** [comment]
The repo could definitely use a real README. To be honest we hadn't really thought we'd have other folks contributing and so hadn't put in the time. Any changes you'd like to make to the README to make helping out here easier would be much appreciated.

**Comment by rudeboybert** [comment]
Cool, I'll include a barebones README in my PR.

As for adding the https://www.updatingdata.org/ to the repo's about page, only an Admin can do that by clicking the gear that should show up next to "About" in the image below -> Website

<img width="454" alt="Screen Shot 2021-04-02 at 9 53 31 AM" src="https://user-images.githubusercontent.com/4574203/113421648-78bf1480-9399-11eb-8cd9-4dee12253c7c.png">

**Comment by ethanwhite** [comment]
Done.
